# FEATURE ADDED: Response Playbook Checklist

PLAYBOOKS = {
    "brute_force": [
        "Confirm source IP is external or internal rogue system",
        "Check target account lockout status",
        "Verify MFA is enforced on targeted account",
        "Block source IP at perimeter firewall if malicious confirmed",
        "Reset credentials for targeted account",
        "Notify affected user and their manager",
        "Document all IOCs and escalate if attack persists",
    ],
    "port_scan": [
        "Confirm source IP identity (internal vs external)",
        "Identify which ports and services were scanned",
        "Check if source IP has prior alerts in last 24 hours",
        "Determine if scanned services are internet-facing",
        "Block source IP if external and confirmed malicious",
        "Review firewall rules for unnecessarily exposed ports",
        "Document scan pattern and correlate with other alerts",
    ],
    "phishing_email": [
        "Quarantine the phishing email from all mailboxes",
        "Extract and document all IOCs (sender, links, attachments)",
        "Check if any users clicked links or opened attachments",
        "Block sender domain and URLs at email gateway",
        "Scan endpoints of any users who interacted",
        "Notify affected users with awareness guidance",
        "Submit IOCs to threat intelligence platform",
    ],
    "malware_download": [
        "Isolate the affected endpoint immediately",
        "Identify the malware file (name, hash, path)",
        "Determine download source (URL, email, USB)",
        "Run endpoint scan on isolated machine",
        "Check lateral movement from affected host",
        "Preserve disk image for forensic analysis",
        "Remediate and restore from clean backup",
    ],
    "suspicious_login": [
        "Verify if login was authorized by the account owner",
        "Check login location and device for anomalies",
        "Review recent activity on the account",
        "Force password reset and re-enroll MFA",
        "Review all sessions and revoke suspicious ones",
        "Check for data access or exfiltration post-login",
        "Document findings and notify account owner",
    ],
    "powershell_execution": [
        "Identify the process that spawned PowerShell",
        "Capture and decode any base64-encoded commands",
        "Check if execution policy was bypassed",
        "Determine if script downloaded external content",
        "Scan the host for persistence mechanisms",
        "Isolate host if malicious payload confirmed",
        "Document decoded commands and parent process chain",
    ],
    "command_and_control": [
        "Identify the external C2 IP or domain",
        "Block the C2 endpoint at firewall and DNS",
        "Isolate the beaconing host from network",
        "Identify the process responsible for C2 traffic",
        "Check for data exfiltration from the host",
        "Scan for implants or backdoors on the host",
        "Preserve memory dump for forensic analysis",
    ],
    "web_attack": [
        "Identify the vulnerable endpoint and parameter",
        "Check if the attack was successful or blocked",
        "Review web server logs for extent of access",
        "Patch or WAF-block the vulnerable endpoint",
        "Check for webshells or unauthorized file uploads",
        "Review database for signs of SQL injection access",
        "Document payload and update WAF rules",
    ],
    "lateral_movement": [
        "Map all hosts accessed by the source account or IP",
        "Disable the compromised account immediately",
        "Isolate all affected hosts from network",
        "Identify credentials used for lateral movement",
        "Reset all passwords associated with lateral path",
        "Check for persistence on each accessed host",
        "Build a full timeline of attacker movement",
    ],
    "dns_tunneling": [
        "Identify the suspicious domain being queried",
        "Block the domain at DNS resolver level",
        "Capture and analyze DNS query payload data",
        "Identify the host generating the DNS traffic",
        "Isolate the host and terminate the process",
        "Check for data exfiltration volume via DNS",
        "Review DNS logs for other anomalous domains",
    ],
    "privilege_escalation": [
        "Identify the method used for escalation",
        "Revoke elevated privileges from the account immediately",
        "Patch the exploited vulnerability if known CVE",
        "Check what actions were taken with elevated rights",
        "Review audit logs for unauthorized changes",
        "Check for persistence mechanisms installed",
        "Document escalation path and remediate",
    ],
    "data_exfiltration": [
        "Identify the destination IP, domain, or service",
        "Block the exfiltration endpoint immediately",
        "Determine what data was exfiltrated and volume",
        "Isolate the source host from network",
        "Preserve all logs and network captures",
        "Notify legal and compliance teams if required",
        "Initiate breach assessment and documentation",
    ],
}
